spring:
  config:
    activate:
      on-profile: local
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379

---

spring:
  config:
    activate:
      on-profile: dev
  rabbitmq:
    host: b-6e6a9f6d-7a15-4e16-85dc-704e4a9675e9.mq.ap-northeast-2.amazonaws.com
    port: 5671
    username: keewe
    password: ilovekeewe98
    ssl:
      enabled: true
    redis:
      host: 152.67.199.234
      port: 6379