spring:
  profiles:
    include: domain, core


---

spring:
  config:
    activate:
      on-profile: local

env:
  node:
    name: ${ENV_NODE_NAME:NA}


---


spring:
  config:
    activate:
      on-profile: dev

env:
  node:
    name: ${ENV_NODE_NAME:NA}

---